### ISSUE TITLE
ViewBox value is wrong in svg image

### ISSUE THREAD

**Issue by mnmaltsev** [szimek/signature_pad#648]
From 4.0.0 version when use toDataURL("image/svg+xml") function resulting svg viewBox value has wrong height and width. The problem is 
[`viewBox="${minX} ${minY} ${this.canvas.width} ${this.canvas.height}"`](https://github.com/szimek/signature_pad/blob/master/src/signature_pad.ts#:~:text=%60%20viewBox%3D%22%24%7BminX%7D%20%24%7BminY%7D%20%24%7Bthis.canvas.width%7D%20%24%7Bthis.canvas.height%7D%22%60%20%2B)
Width should be `this.canvas.width / ratio` and height should be `this.canvas.height / ratio` as in previous version.

Bug can be reproduced by [demo](http://szimek.github.io/signature_pad/)
![image](https://user-images.githubusercontent.com/47325852/188425517-15364df4-3bb5-4e87-8edd-7ffccdd17807.png)
![image](https://user-images.githubusercontent.com/47325852/188426395-b571eb88-9a1c-4cc1-8d5e-246120d4a771.png)

**Comment by UziTech** [comment]
This would cause the issue in #411 wouldn't it?

**Comment by mnmaltsev** [comment]
I can not imagine the case when somebody need not drawable space. As you see in your demo it adds empty spaces on bottom and right. I use the same code to handling high DPI 
```
function resizeCanvas() {
    const ratio =  Math.max(window.devicePixelRatio || 1, 1);
    canvas.width = canvas.offsetWidth * ratio;
    canvas.height = canvas.offsetHeight * ratio;
    canvas.getContext("2d").scale(ratio, ratio);
    signaturePad.clear(); // otherwise isEmpty() might return incorrect value
}
```
as result drawable area scaled and I want to use result svg image as it was in creation step to display it for the user without additional operations with svg.
Is it possible to add option to cut ViewBox size to initial drawable area as in previous version?
This option will satisfy desires of everybody)

**Comment by UziTech** [comment]
I am having a hard time reproducing the issue in #411. I'm thinking this was fixed before that was merged. I think it would be ok to change it back. If you want to create a PR that would be very helpful 😁👍

**Comment by dnlrbz** [comment]
@UziTech the issue is still happening in version. `"signature_pad": "^4.1.4"`, the viewBox, width and height of an SVG is wrong, because of window.devicePixelRatio. Could you please add ratio parameter to the toSVG() method?

**Comment by UziTech** [comment]
@dnlrbz the best way to get this fixed would be to create a new issue and provide some code or a repo that can reproduce it along with a video.
