### ISSUE TITLE
issues in latest Google Chrome 117

### ISSUE THREAD

**Issue by zhil** [szimek/signature_pad#734]
I want to report a bug - Library is not working in latest Google Chrome 117

**Steps to reproduce** - Current demo https://szimek.github.io/signature_pad/ gif
![bug](https://github.com/szimek/signature_pad/assets/981783/2929b57b-ee60-4145-a486-4b1c24140c48)

Its working just fine in Firefox and worked just fine before Google Chrome update.

**Comment by UziTech** [comment]
Looks like this is fixed in Chrome 118. I don't think there is anything we can change to fix this.

**Comment by zhil** [comment]
@UziTech I just updated Google Chrome to latest 118.0.5993.88 - and bug still exists.

I founded another strange thing by accident - when I resize Google Chrome signatured "converted to normal". But if I continue drawing - I got the same issue again (until I resize window).

![bug](https://github.com/szimek/signature_pad/assets/981783/475880a0-24bf-4a3b-9450-f1cbdd74c653)


> This type of bug would need to be reported to Chrome.

Well, probably - yes. But it will be good if somebody will give me hint about more exact definition of bug. Like "function .... is not working correctly and return .... instead of .....".

Not sure I am able to do it without understanding of internal library implementation. 

I consider this bug pretty urgent - basically all google chrome users with recent browser are affected.
Will appreciate some help OR hints for first steps direction in debug.

**Comment by UziTech** [comment]
> basically all google chrome users with recent browser are affected

This seems to only be a bug on Chrome on linux. So that reduces the footprint quite a bit.

> Another idea - since signature is "fixed" on window resize - its probably possible to "hotfix it in runtime" by force calling resize

Ya you can probably do this without any changes to signature_pad by calling resize on [afterUpdateStroke](https://github.com/szimek/signature_pad#events)

You can opt in with something like this:

```js
signaturePad.addEventListener("afterUpdateStroke", () => {
  window.resize();
});
```

**Comment by zhil** [comment]
<details>
  <summary>TL;DR - I failed to patch this issue</summary>

  1) window doesnt have "resize" function. I tried resizeTo, resizeBy,  or something like
  ```
  window.dispatchEvent(new Event('resize'));
  ```
  but resize wasnt called :(

  2) trigger resize is probably not an option, because according to
  https://stackoverflow.com/questions/3641648/the-javascript-resizeto-function-not-working-in-chrome-and-opera

  > The resizeTo method is disabled by default in several browsers, and I know that it can also be manually disabled in Firefox.

  > It has been widely misused, so most browser vendors feel that it should be disabled, or at least a user controllable option.

  3) I checked different Canvas API https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API and cant find anything related to re-draw. I tried a couple weird hacks from internet (like clearRect or add small elements) - they didnt work for me

  4) I updated Chrome to 119.0.6045.159 - it didnt help

</details>

But I actually founded reasons for it - disabling "Accelerated 2D canvas" in chrome://flags/ solve this issue
![image](https://github.com/agilgur5/react-signature-canvas/assets/981783/8d33dd3b-88b5-4bcf-ab53-341f55f069fd)

The problem is that its enabled by default and I cant find any ways to detect that value (probably, its not possible - https://stackoverflow.com/questions/6603274/how-to-determine-whether-browser-provides-hardware-acceleration-for-html5-canvas )

This bug was reported by our users, pretty sure, that ubuntu is not only one platform affected.

@UziTech Any ideas how to detect this bug in run-time from javascript?

**Comment by zhil** [comment]
I have setuped Chromium with exactly the same version of the engine - 119.0.6045.159
default values for canvas related settings are the same

![image](https://github.com/szimek/signature_pad/assets/981783/5cb56836-b865-4f84-808b-2c4eb1c99987)

And online demo https://szimek.github.io/signature_pad/ works just fine.

The same version of the engine in Google Chrome is not working.

Do you know about any issues tracker for Google Chrome? I tried to submit issue via "Report a problem" in browser, but didnt get anything like issue url etc.

**Comment by UziTech** [comment]
You can try https://bugs.chromium.org/p/chromium/issues/list
